/// Writing prompt data, keyed by locale code and category.
///
/// Each map entry: `category key` → `List<String>` of prompts.
const Map<String, Map<String, List<String>>> kWritingPrompts = {
  'en': {
    'general': [
      'What is on your mind right now?',
      'Describe your day in three words — then explain each.',
      'What decision did you make today, and why?',
      'What is one thing you want to remember about today?',
      'What surprised you today?',
      'How did you spend your energy today?',
      'What would you do differently if you could replay today?',
      'What was the highlight of your day?',
      'What is something you observed that you normally overlook?',
      'What conversation stayed with you today?',
    ],
    'reflection': [
      'What belief have you changed recently, and what changed it?',
      'What is a fear you have been avoiding? What would happen if you faced it?',
      'Where are you holding yourself back right now?',
      'What does "success" mean to you at this moment in life?',
      'What would your future self thank you for doing today?',
      'What pattern keeps showing up in your life lately?',
      'What lesson took you the longest to learn?',
      'In what area of your life are you most honest with yourself?',
      'What does your inner critic say most often? Is it right?',
      'What relationship in your life needs more attention right now?',
    ],
    'gratitude': [
      'Name three people who made your life better this week.',
      'What small, everyday thing are you grateful for that you usually take for granted?',
      'What challenge are you secretly grateful for?',
      'What is something about yourself you appreciate today?',
      'What is a memory that always makes you smile?',
      'What piece of technology made your life easier this week?',
      'Who taught you something valuable recently?',
      'What place or space makes you feel safe or at peace?',
      'What opportunity came your way that you almost missed?',
      'Write a thank-you note to a past version of yourself.',
    ],
    'creativity': [
      'Describe an imaginary world where your biggest problem does not exist.',
      'Write a short scene from the perspective of someone who inspires you.',
      'If your current mood were a weather pattern, what would it look like?',
      'Invent a new word for an emotion you often feel but cannot name.',
      'Write the opening lines of the book of your life.',
      'Describe your ideal day in full detail — morning to night.',
      'If you could send a letter to any historical figure, what would you say?',
      'Write about a door you have not yet opened.',
      'Describe yourself through the eyes of your closest friend.',
      'If your life were a film, what genre would it be right now, and why?',
    ],
  },
  'de': {
    'general': [
      'Was beschäftigt dich gerade?',
      'Beschreibe deinen Tag in drei Wörtern — und erkläre jedes davon.',
      'Welche Entscheidung hast du heute getroffen, und warum?',
      'Was möchtest du von heute im Gedächtnis behalten?',
      'Was hat dich heute überrascht?',
      'Wofür hast du heute deine Energie eingesetzt?',
      'Was würdest du heute anders machen, wenn du den Tag wiederholen könntest?',
      'Was war der schönste Moment deines Tages?',
      'Was hast du beobachtet, das du sonst übersehen hättest?',
      'Welches Gespräch hat dich heute begleitet?',
    ],
    'reflection': [
      'Welche Überzeugung hast du zuletzt verändert — und was hat sie verändert?',
      'Welche Angst weichst du gerade aus? Was würde passieren, wenn du ihr begegnest?',
      'Wo hältst du dich selbst gerade zurück?',
      'Was bedeutet „Erfolg" für dich in diesem Lebensabschnitt?',
      'Wofür würde dein zukünftiges Ich dir heute danken?',
      'Welches Muster taucht in deinem Leben gerade immer wieder auf?',
      'Welche Lektion hat am längsten gedauert, bis du sie gelernt hast?',
      'In welchem Bereich bist du am ehrlichsten zu dir selbst?',
      'Was sagt dein innerer Kritiker am häufigsten? Hat er recht?',
      'Welche Beziehung in deinem Leben braucht gerade mehr Aufmerksamkeit?',
    ],
    'gratitude': [
      'Nenne drei Menschen, die dein Leben diese Woche besser gemacht haben.',
      'Welche Kleinigkeit im Alltag schätzt du, die du sonst für selbstverständlich hältst?',
      'Für welche Herausforderung bist du heimlich dankbar?',
      'Was schätzt du heute an dir selbst?',
      'An welche Erinnerung denkst du gerne zurück?',
      'Welche Technologie hat dein Leben diese Woche einfacher gemacht?',
      'Wer hat dir kürzlich etwas Wertvolles beigebracht?',
      'Welcher Ort gibt dir ein Gefühl von Sicherheit oder Ruhe?',
      'Welche Gelegenheit hast du fast verpasst?',
      'Schreibe einen Dankesbrief an eine frühere Version von dir.',
    ],
    'creativity': [
      'Beschreibe eine Welt, in der dein größtes Problem nicht existiert.',
      'Schreibe eine kurze Szene aus der Perspektive einer Person, die dich inspiriert.',
      'Wenn deine aktuelle Stimmung ein Wettermuster wäre — wie würde es aussehen?',
      'Erfinde ein neues Wort für ein Gefühl, das du oft hast, aber nicht benennen kannst.',
      'Schreibe den Eröffnungssatz des Buches deines Lebens.',
      'Beschreibe deinen perfekten Tag — von morgens bis abends.',
      'Wenn du einer historischen Persönlichkeit einen Brief schreiben könntest — was würdest du sagen?',
      'Schreibe über eine Tür, die du noch nicht geöffnet hast.',
      'Beschreibe dich selbst durch die Augen deines besten Freundes.',
      'Wenn dein Leben gerade ein Film wäre — welches Genre wäre es, und warum?',
    ],
  },
};
